/*
 * Copyright (c) Meta Platforms, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facebook_cgsql_CQLResultSet */

#ifndef _Included_com_facebook_cgsql_CQLResultSet
#define _Included_com_facebook_cgsql_CQLResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_facebook_cgsql_CQLResultSet_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getBoolean
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_cgsql_CQLResultSet_getBoolean
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getInteger
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_facebook_cgsql_CQLResultSet_getInteger
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getLong
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_facebook_cgsql_CQLResultSet_getLong
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getString
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_facebook_cgsql_CQLResultSet_getString
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getDouble
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_com_facebook_cgsql_CQLResultSet_getDouble
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getBlob
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_facebook_cgsql_CQLResultSet_getBlob
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    isNull
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_cgsql_CQLResultSet_isNull
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_facebook_cgsql_CQLResultSet_getCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    rowHashCode
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_facebook_cgsql_CQLResultSet_rowHashCode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    rowsEqual
 * Signature: (JIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_cgsql_CQLResultSet_rowsEqual
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    rowsSame
 * Signature: (JIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_cgsql_CQLResultSet_rowsSame
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    copy
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_facebook_cgsql_CQLResultSet_copy
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_facebook_cgsql_CQLResultSet
 * Method:    getIsEncoded
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_cgsql_CQLResultSet_getIsEncoded
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
