/*
 * Copyright (c) Meta Platforms, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestResult */

#ifndef _Included_TestResult
#define _Included_TestResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestResult
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TestResult_open
  (JNIEnv *, jclass);

/*
 * Class:     TestResult
 * Method:    getTestResult
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_TestResult_getTestResult
  (JNIEnv *, jclass);

/*
 * Class:     TestResult
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestResult_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
